# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class CheckabilityOutput(BaseModel):
    reasoning: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    is_checkable: typing.Optional[bool] = None

class HarmPotentialOutput(BaseModel):
    reasoning: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    is_harmful: typing.Optional[bool] = None
    social_fragmentation: typing.Optional["HarmSubScore"] = None
    spurs_action: typing.Optional["HarmSubScore"] = None
    believability: typing.Optional["HarmSubScore"] = None
    exploitativeness: typing.Optional["HarmSubScore"] = None

class HarmSubScore(BaseModel):
    confidence: typing.Optional[float] = None
    reasoning: typing.Optional[str] = None
    is_harmful: typing.Optional[bool] = None

class VerifiabilityOutput(BaseModel):
    reasoning: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    is_verifiable: typing.Optional[bool] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
