# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CheckabilityOutput": types.CheckabilityOutput,
    "stream_types.CheckabilityOutput": stream_types.CheckabilityOutput,

    "types.HarmPotentialOutput": types.HarmPotentialOutput,
    "stream_types.HarmPotentialOutput": stream_types.HarmPotentialOutput,

    "types.HarmSubScore": types.HarmSubScore,
    "stream_types.HarmSubScore": stream_types.HarmSubScore,

    "types.VerifiabilityOutput": types.VerifiabilityOutput,
    "stream_types.VerifiabilityOutput": stream_types.VerifiabilityOutput,


}